import type { Complaint } from './types';

export const complaintsData: Complaint[] = [
  {
    id: '1',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'parked car',
    vehicleType: 'Jeepney',
    licensePlate: 'ABC-1234',
    route: 'Main Street',
    incidentTime: '14:30',
    incidentDate: '2024-07-20',
    description: 'Jeepney illegally parked in a no-parking zone, blocking a fire hydrant.',
    status: 'New',
    complaintType: 'Parking',
  },
  {
    id: '2',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'traffic jam',
    vehicleType: 'Trike',
    licensePlate: 'BUS-5678',
    route: 'Elm Avenue',
    incidentTime: '08:15',
    incidentDate: '2024-07-21',
    description: 'Trike running a red light, causing a near-collision.',
    status: 'New',
    complaintType: 'Traffic',
  },
  {
    id: '3',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'broken window',
    vehicleType: 'Modern PUV',
    licensePlate: 'XYZ-9876',
    route: 'Oak Drive',
    incidentTime: '22:00',
    incidentDate: '2024-07-19',
    description: 'Loud music coming from a parked Modern PUV late at night.',
    status: 'Resolved',
    complaintType: 'Noise',
  },
  {
    id: '4',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'delivery truck',
    vehicleType: 'Van',
    licensePlate: 'TRK-1122',
    route: 'Maple Lane',
    incidentTime: '11:45',
    incidentDate: '2024-07-22',
    description: 'Van double-parked and blocking traffic on a narrow street.',
    status: 'Review',
    complaintType: 'Parking',
  },
  {
    id: '5',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'motorcycle speeding',
    vehicleType: 'Tricycle',
    licensePlate: 'MC-3344',
    route: 'Highway 101',
    incidentTime: '17:00',
    incidentDate: '2024-07-22',
    description: 'Tricycle weaving between lanes at high speed.',
    status: 'Resolved',
    complaintType: 'Traffic',
  },
  {
    id: '6',
    incidentPhotoUrl: 'https://picsum.photos/600/400',
    incidentPhotoAiHint: 'graffiti wall',
    vehicleType: 'Van',
    licensePlate: 'VAN-D4L',
    route: 'Art District',
    incidentTime: '01:20',
    incidentDate: '2024-07-18',
    description: 'Vehicle appears to have been vandalized with graffiti.',
    status: 'Review',
    complaintType: 'Vandalism',
  },
];
